routes/web.php
    if ($persona = $cat->vehiculo->persona) {
      $cat->persona_dni = $persona->dni;
      $cat->save();
    }elseif ($empresa = $cat->vehiculo->empresa) {
      $cat->empresa_ruc = $empresa->ruc;
      $cat->save();
    }
    if ($duplicado = $cat->duplicado) {
      if ($persona = $cat->vehiculo->persona) {
        $duplicado->persona_dni = $persona->dni;
        $duplicado->save();
      }elseif ($empresa = $cat->vehiculo->empresa) {
        $duplicado->empresa_ruc = $empresa->ruc;
        $duplicado->save();
      }
    }
  }

  return "listo";
});

Route::get('actualizar', 'PadronController@actualizar');

// Rutas dee prueba y llenado de la Base de Datos
Route::get('enviar-sms', 'SmsController@enviarSms');

Route::get('padron/{nombre}', 'PadronController@subirPadron');

Route::get('subir-distritos', function(){
  Excel::load("public/ubigeo.xls", function($archivo){
    $fila = $archivo->get();
    foreach ($fila as $key => $value) {
      $distrito = new \Afocat\Distrito;
      $distrito->nombre = mb_strtoupper($value->distrito);
      $distrito->provincia_id = $value->provincia;
      $distrito->save();
    }
  })->get();
  return redirect('/');
});

Route::get('email', function(){
  Mail::to('dante.e.cortes@gmail.com')->send(new BienvenidaEmail('Dante Cortés'));
  return "email enviado";
});

// Ruta de inicio, si no hay ningun usuario administrador registrado muestra
// la vista de primera configuración del sistema, caso contrario muestra la
// vista para loguearse.
Route::get('/', function(){
  $usuario = Afocat\User::where('area', '0')->get()->first();
  if (isset($usuario)) {
    return redirect('/login');
  } else {
    return view('inicio.bienvenida');
  }
});

// Muestra el panel de inicio del administrador
Route::get('administrador', function(){
  return view('panel.paneladministrador');
});

// Muestra el panel de inicio del area de siniestros.
Route::get('siniestros', function(){
  return view('panel.panelsiniestros');
});

// Muestra el panel de inicio del área de afiliación.
Route::get('afiliacion', function () {
  return view('panel.panelafiliacion');
});

Route::get('afiliacion/filtrar-todos', 'AfocatController@filtrarTodos');

Route::resource('usuario', 'UsuarioController');

Route::resource('persona', 'PersonaController');

Route::post('persona/filtrar-todos', 'PersonaController@filtrarTodos');

Route::resource('empresa', 'EmpresaController');

Route::resource('vehiculo', 'VehiculoController');

// Filtra los vehiculos afiliados entre dos fechas.
Route::post('vehiculo/filtrar-todos', 'VehiculoController@filtrarTodos');

Route::resource('afocat', 'AfocatController');

Route::post('calcular-excedente', 'AfocatController@calcularExcedente');

// exporta los CAT's vencidos a un excel.
Route::get('exportar-vencidos', 'ExcelController@exportarCatsVencidos');

//muestra un formulario para descargar un excel SBS.
Route::get('padron-sbs', 'AfocatController@mostrarFormularioExportarSbs');

// Exporta los CAT's de un mes a un excel en formato de SBS.
Route::post('excel-interno', 'AfocatController@exportarExcelInterno');

//muestra un formulario para descargar un excel del Padrón general.
Route::get('padron-general', 'AfocatController@mostrarFormularioExportarGeneral');

// Exporta los CAT's de un mes a un excel en formato de Padrón General.
Route::post('excel-general', 'AfocatController@exportarExcelGeneral');

//muestra un formulario para descargar un excel del Padrón conn Vendedores.
Route::get('padron-vendedores', 'AfocatController@mostrarFormularioExportarVendedores');

// Exporta los CAT's de un mes a un excel en formato de Padrón General con Vendedores.
Route::post('excel-vendedores', 'AfocatController@exportarExcelVendedores');

Route::resource('anulado', 'AnuladoController');

Route::resource('duplicado', 'DuplicadoController');

Route::resource('excel', 'ExcelController');

Route::post('buscar-cat', 'DuplicadoController@buscarCat');

Route::post('vehiculo/buscar-dni', 'VehiculoController@otro');

Route::post('buscar-auto', 'VehiculoController@buscarAuto');

Route::resource('accidente', 'AccidenteController');

Route::post('buscar-distrito', 'AccidenteController@buscarDistrito');

Route::post('accidente/buscar-auto', 'AccidenteController@buscarAuto');

Route::resource('accidentado', 'AccidentadoController');

Route::post('accidentado/buscar-accidente', 'AccidentadoController@buscarAccidente');

Route::resource('gasto', 'GastoController');

Route::resource('pago', 'AccidentadoGastoController');

Route::post('pago/accidentado', 'AccidentadoGastoController@buscarAccidentado');

Route::get('siniestros/excel', 'AccidentadoGastoController@buscarMes');

Route::post('siniestros/excel', 'AccidentadoGastoController@descargarExcel');

Route::get('indemnizaciones', 'AccidentadoGastoController@indemnizaciones');

// Controlador que envia un email de felicitacion por cumpleaños a todos los que
// cumplen años en el día.
Route::get('felicitar-todos-email', 'EmailController@felicitarTodos');

// Controllador que envía un sms de felicitaciones por cumpleaños a todos los que
// cumplen años este día.
Route::get('felicitar-todos-sms', 'SmsController@felicitarTodos');

// Esta ruta muestra una vista con todos los que cumplen años en el día.
Route::get('cumpleanieros', 'EmailController@mostrarCumpleanieros');

// controlador para enviar email de felicitacion por cumpleaños a una persona.
Route::get('felicitar-cumpleanios-email/{dni}', 'EmailController@felicitarCumpleanios');

// controlador para enviar sms de felicitacion por cumpleaños a una persona.
Route::get('felicitar-cumpleanios-sms/{dni}', 'SmsController@felicitarCumpleanios');

// Método que envía un email recordatorio a todos los que tiene CAT´s por vencer
// en esta semana.
Route::get('recordar-todos-email', 'EmailController@recordarTodos');

// Método que envía un sms recordatorio a todos los que tiene CAT´s por vencer
// en esta semana.
Route::get('recordar-todos-sms', 'SmsController@recordarTodos');

// Muestra la vista con todos los afiliados que tienen CAT's que estan por vencer
// en la semana
Route::get('recordar', 'AfocatController@mostrarPorVencer');

// Enviar email recordatorio a una persona que se le va a vencer el CAT en esta semana.
Route::get('recordar-email/{dni}', 'EmailController@recordar');

// Enviar sms recordatorio a una persona que se le va a vencer el CAT en esta semana.
Route::get('recordar-sms/{dni}', 'SmsController@recordar');

// Método que envía un email recordatorio a todos los que tienen CAT´s vencidos.
Route::get('vencidos-todos-email', 'EmailController@recordarVencidos');

// Método que envía un sms recordatorio a todos los que tiene CAT´s vencidos.
Route::get('vencidos-todos-sms', 'SmsController@recordarVencidos');

// Muestra la vista con todos los afiliados que tienen CAT's que estan por vencer
// en la semana
Route::get('vencidos', 'AfocatController@mostrarVencidos');

// Enviar email recordatorio a una persona que se le va a vencer el CAT en esta semana.
Route::get('vencidos-email/{dni}', 'EmailController@vencidos');

// Enviar sms recordatorio a una persona que se le va a vencer el CAT en esta semana.
Route::get('vencidos-sms/{dni}', 'SmsController@vencidos');

// Muestra una vista con opciones para mostrar estadisticas entre dos fechas.
Route::get('estadisticas', 'EstadisticaController@inicio');

// Busca los resultados de la estadistica solicitada.
Route::post('estadistica', 'EstadisticaController@buscar');

// Mostrar formulario para buscar Vehiculo.
Route::get('consulta-sbs', 'AfocatController@mostrarFormularioBuscarVehiculo');

// Método para buscar un vehiculo.
Route::post('buscar-vehiculo-web', 'AfocatController@buscarVehiculo');

// muestra un formukario para subir un padron de afiliados.
Route::get('subir-padron', 'AfocatController@mostrarFormularioSubirPadron');

// sube un padron de afiliados al sistema
Route::post('subir-padron', 'AfocatController@subirPadron');

// Muestra un formulario para guardar un excel de siniestros.
Route::get('subir-siniestros', 'AccidentadoGastoController@mostrarFormularioSubirSiniestros');

// sube un padron de siniestros al sistema y a la BD
Route::post('subir-siniestros', 'AccidentadoGastoController@subirSiniestros');

Route::get('padron-siniestros/{nombre}', 'PadronController@subirSiniestros');

Auth::routes();

Route::get('/home', 'HomeController@index');

// Rutas para listar registros en las tablas bootstrip
Route::post('buscar-afiliado', 'AfiliadoController@buscarAfiliado');
Route::post('buscar-empresa', 'EmpresaController@buscarEmpresa');
Route::post('buscar-vehiculo', 'VehiculoController@buscarVehiculo');
Route::post('buscar-certificado', 'AfocatController@buscarCertificado');
Route::post('listar-accidentes', 'AccidenteController@listarAccidentes');

// Rutas para exportar padrones con registros entre un rango de fechas.
Route::post('exportar-sunat-rango', 'AfocatController@ExportarSunatRango');
Route::post('exportar-sbs-rango', 'AfocatController@ExportarSbsRango');
Route::post('exportar-general-rango', 'AfocatController@ExportarGeneralRango');
Route::post('exportar-vendedores-rango', 'AfocatController@ExportarVendedoresRango');

// Rutas para exportar reporte diario.
Route::get('reporte-diario', 'AfocatController@mostrarFormularioReporteDiario');
Route::post('exportar-diario', 'AfocatController@exportarReporteDiario');

Route::get('base', function(){
   
    $afocats = DB::table('afoc_afocats as a')
        ->join('afoc_afocats_real as ar', 'ar.numero', '=', 'a.numero')
        ->select(
            'ar.numero as numero_real',
            'a.numero as numero',
            'ar.extraordinario as extraordinario',
            'ar.vendedor as vendedor'
        )
        ->get();
    
    foreach($afocats as $a){
        
        $actualizar = \Afocat\Afocat::find($a->numero);
        $actualizar->extraordinario = $a->extraordinario;
        $actualizar->vendedor = strtoupper($a->vendedor);
        $actualizar->save();
        echo $a->numero."<br>";
    }
});

app/AccidentadoGasto.php
<?php

namespace Afocat;

use Illuminate\Database\Eloquent\Model;

class AccidentadoGasto extends Model
{
  protected $table = 'afoc_accidentado_gasto';

  public $timestamps = false;

  public function getFechaLimiteAttribute($value){
    if (isset($value)) {
      $value = date('d/m/Y', strtotime($value));
    }
    return $value;
  }

  public function accidentado(){
    return $this->belongsTo('\Afocat\Accidentado', 'accidentado_codigo', 'codigo');
  }

  public function gasto(){
    return $this->belongsTo('\Afocat\Gasto', 'gasto_id', 'id');
  }
}

app/Gasto.php
<?php

namespace Afocat;

use Illuminate\Database\Eloquent\Model;

class Gasto extends Model
{
  protected $table = 'afoc_gastos';

  public $timestamps = false;
  
}

app/Http/Controllers/GastoController.php
<?php

namespace Afocat\Http\Controllers;

use Afocat\Gasto;
use Illuminate\Http\Request;

class GastoController extends Controller
{

  public function index(){
    $gastos = Gasto::all();
    return view('gasto.inicio')->with('gastos', $gastos);
  }

  public function create(){

  }

  public function store(Request $request){

    $gasto = new Gasto;
    $gasto->nombre = mb_strtoupper($request->nombre);
    $gasto->save();
    return redirect('gasto')->with('correcto', 'EL GASTO SE AGREGÓ EXITOSAMENTE');
  }

  public function show(Gasto $gasto){
      //
  }

  public function edit(Gasto $gasto)
  {
      //
  }

  public function update(Request $request, Gasto $gasto)
  {
      //
  }

  public function destroy(Gasto $gasto){
    $gasto->delete();
    return redirect('gasto')->with('advertencia', 'SE BORRÓ EL TIPO DE GASTO: '.$gasto->nombre.'.');
  }
}

resources/views/gasto/indemnizados.blade.php
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Plantilla elaborada para el cliente AFOCAT León de Huánuco">
    <meta name="author" content="Dante Esteban Cortés">
    @yield('metas')
    <link rel="icon" href="{{ url('favicon.ico') }}">

    <title>Indemnizaciones</title>

    <!-- Bootstrap core CSS -->
    {!!Html::style('bootstrap/css/bootstrap.min.css')!!}

    <!-- Custom styles for this template -->
    {!!Html::style('css/afiliacion.css')!!}



    @yield('estilos')

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src='https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Inicio de Contenido -->
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <table class="table table-bordered table-condensed">
            <thead>
              <tr>
                <th>DNI</th>
                <th>INDEMNIZADO</th>
                <th>N° CAT</th>
                <th>FECHA DEL ACCIDENTE</th>
                <th>LUGAR DEL ACCIDENTE</th>
                <th>N° PLACA</th>
                <th>FECHA LIMITE DEL COBRO</th>
              </tr>
            </thead>
            <tbody>
              @foreach($indemnizados as $indemnizado)
                <tr>
                  <td>{{$indemnizado->accidentado->dni}}</td>
                  <td>{{$indemnizado->accidentado->nombre}}</td>
                  <td>{{\Afocat\Afocat::where('vehiculo_placa', $indemnizado->accidentado->accidente->vehiculo->placa)
										->orderBy('inicio_certificado', 'desc')->first()->numero}}</td>
                  <td>{{$indemnizado->accidentado->accidente->ocurrencia}}</td>
                  <td>HUÁNUCO -
                    {{$indemnizado->accidentado->accidente->provincia}} -
                    {{$indemnizado->accidentado->accidente->zona}}
                  </td>
                  <td>{{$indemnizado->accidentado->accidente->vehiculo->placa}}</td>
                  <td>{{$indemnizado->fecha_limite}}</td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Ubicado al final del documento para que la página cargue rápido -->
    {!!Html::script('js/jquery.min.js')!!}
    {!!Html::script('bootstrap/js/bootstrap.min.js')!!}

  	@yield('scripts')
	</body>
</html>

resources/views/gasto/inicio.blade.php
@extends('plantillasiniestros')

@section('titulo')
Tipos de Gasto
@stop

@section('estilos')

@stop

@section('contenido')
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    @if(Session::has('correcto'))
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Excelente!</strong> {{Session::get('correcto')}}
      </div>
    @elseif(Session::has('error'))
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Error!</strong> {{Session::get('error')}}
      </div>
    @elseif(Session::has('advertencia'))
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Cuidado!</strong> {{Session::get('advertencia')}}
      </div>
    @endif
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Tipos de Gastos</h3>
      </div>
      <div class="table-responsive">
        <table id="gastos" class="table table-bordered">
          <thead>
            <tr>
              <th>TIPO</th>
              <th>BORRAR</th>
            </tr>
          </thead>
          <tbody>
            @foreach($gastos as $gasto)
            <tr>
              <td>{{$gasto->nombre}}</td>
              <td>
                <button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#borrar{{$gasto->id}}">
                  <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> Borrar
                </button>
                <div class="modal fade" id="borrar{{$gasto->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content" style="background-color: #FF3737">
                      <div class="modal-header">
                        <button class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Borrar Tipo de Gasto {{$gasto->nombre}}</h4>
                      </div>
                      <div class="modal-body">
                        {!!Form::open(['url'=>'gasto/'.$gasto->id, 'class'=>'form-horizontal', 'method'=>'delete'])!!}
                        <p>Esta a punto de borrar el tipo de gasto {{$gasto->nombre}}, y con eso se eliminarán todos los gastos pagados a los accidentados
                          de este tipo de gasto.</p>
                        <p>Si esta seguro de esta decición continue en el botón Borrar de lo contrario pulse Cancelar</p>
                      </div>
                      <div class="modal-footer">
                        <button class="btn btn-default" type="button" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Borrar</button>
                        {!!Form::close()!!}
                      </div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Nuevo Tipo Gasto</h3>
      </div>
      <div class="panel-body">
        {!!Form::open(['url'=>'gasto', 'class'=>'form-horizontal', 'method'=>'post'])!!}
          <div class="form-group">
            {!!Form::label('Nombre*:', null, ['class'=>'control-label col-sm-2'])!!}
            <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
              {{Form::text('nombre', null, ['class'=>'form-control input-sm mayuscula', 'placeholder'=>'NOMBRE', 'required'=>''])}}
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 col-sm-offset-2">
              {{Form::button('Guardar', ['class'=>'btn btn-primary btn-sm', 'type'=>'submit'])}}
            </div>
          </div>
        {!!Form::close()!!}
      </div>
    </div>
  </div>
</div>
@stop

@section('scripts')

@stop

resources/views/gasto/subirSiniestros.blade.php
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Plantilla elaborada para el cliente AFOCAT León de Huánuco">
    <meta name="author" content="Dante Esteban Cortés">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{ url('favicon.ico') }}">

    <title>Subir Siniestros</title>

    <!-- Bootstrap core CSS -->
    {!!Html::style('bootstrap/css/bootstrap.min.css')!!}

    <!-- Custom styles for this template -->
    {!!Html::style('css/afiliacion.css')!!}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src='https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Inicio de Contenido -->
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="panel panel-default">
            <div class="panel-body">
              {!!Form::open(['url'=>'subir-siniestros', 'class'=>'form-inline', 'enctype'=>'multipart/form-data'])!!}
                <div class="form-group">
                  {!!Form::label('Padrón:', null, ['class'=>'control-label'])!!}
                  {!!Form::file('padron', null, ['class'=>'form-control input-sm', 'required'=>'', 'id'=>'padron'])!!}
                </div>
                {!!Form::button('Subir', ['class'=>'btn btn-primary btn-sm', 'type'=>'submit', 'id'=>'subir'])!!}
              {!!Form::close()!!}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Ubicado al final del documento para que la página cargue rápido -->
    {!!Html::script('js/jquery.min.js')!!}
    {!!Html::script('bootstrap/js/bootstrap.min.js')!!}


	</body>
</html>